import type { Project, SocialLink, StackItem } from '@/types'

export const SITE_URL = 'https://aydinnasibli.com'
export const EMAIL = 'mail@aydinnasibli.com'

export const PROJECTS: Project[] = [
  {
    n: '01',
    year: '2026',
    title: 'Visuologia',
    subtitle: 'Describe a chart in plain English. Get it back, ready to ship.',
    description:
      'An AI charting tool for people who know their data but not D3. You describe what you want — or drop a CSV, JSON or XLSX — and it returns a real visualisation you can keep refining in conversation. Nineteen chart families, statistical tests that run client-side, Google Sheets bound to live-updating charts, and export to PNG, SVG, PDF, HTML, JSON or CSV.',
    tags: ['Next.js', 'TypeScript', 'OpenAI', 'D3', 'Tailwind', 'PostgreSQL'],
    role: 'Solo build',
    client: 'Self-initiated',
    accent: 'oklch(0.58 0.19 310)',
    accent2: 'oklch(0.92 0.04 310)',
    live: 'https://visualme.vercel.app',
    metrics: [
      { value: '19', label: 'chart families' },
      { value: '6', label: 'export formats' },
      { value: '3', label: 'input formats' },
    ],
    visual: 'dataviz',
    host: 'visualme.vercel.app',
  },
  {
    n: '02',
    year: '2026',
    title: 'The Living Manuscript',
    subtitle: 'A living map of Western philosophical thought.',
    description:
      'An interactive network of philosophers — drag nodes to reposition thinkers, hover a portrait to surface their ideas, click to read the full entry. Built as a quiet reading room around the history of ideas: lineage, schools, thematic paths, and the threads that connect them across centuries.',
    tags: ['Next.js', 'React', 'TypeScript', 'Tailwind', 'Framer Motion', 'MongoDB'],
    role: 'Solo build',
    client: 'Self-initiated',
    accent: 'oklch(0.55 0.18 268)',
    accent2: 'oklch(0.92 0.02 80)',
    live: 'https://philoproj.vercel.app',
    metrics: [
      { value: '10', label: 'thinkers' },
      { value: '4', label: 'eras mapped' },
      { value: '5', label: 'ways to browse' },
    ],
    visual: 'manuscript',
    host: 'philoproj.vercel.app',
  },
  {
    n: '03',
    year: '2026',
    title: 'Testcentre',
    subtitle: 'Adaptive exam prep that reads the student, not the syllabus.',
    description:
      'An academic exam platform covering SAT, IELTS, TOEFL, GMAT, GRE and the national university entrance exam. It opens with a diagnostic across eleven dimensions, then builds a thirty-minute daily plan that reshapes itself as scores move. Full-length simulations run in real exam format, and every question carries a video explanation.',
    tags: ['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Tailwind', 'Vercel'],
    role: 'Engineer & designer',
    client: 'Testcentre',
    accent: 'oklch(0.52 0.16 250)',
    accent2: 'oklch(0.91 0.04 245)',
    live: 'https://www.testcentre.az',
    metrics: [
      { value: '11', label: 'diagnostic axes' },
      { value: '6', label: 'exam formats' },
      { value: '30m', label: 'daily plan' },
    ],
    visual: 'diagnostic',
    host: 'testcentre.az',
  },
  {
    n: '04',
    year: '2025',
    title: 'Biologium',
    subtitle: 'Turkish high-school biology, rebuilt as a study loop.',
    description:
      'A structured curriculum for TYT and AYT biology, grades nine through twelve. Each topic runs a six-step loop — animation, explanation, embedded questions, timed quiz, summary card, then flashcards scheduled by SM-2 spaced repetition. Answers are validated server-side, progress updates live, and study groups compete on weekly rankings.',
    tags: ['Next.js', 'TypeScript', 'MongoDB', 'Tailwind', 'SM-2', 'Vercel'],
    role: 'Solo build',
    client: 'Biologium',
    accent: 'oklch(0.55 0.14 155)',
    accent2: 'oklch(0.91 0.05 150)',
    live: 'https://www.biologium.com',
    metrics: [
      { value: '28', label: 'topics' },
      { value: '7', label: 'units' },
      { value: '6', label: 'step loop' },
    ],
    visual: 'curriculum',
    host: 'biologium.com',
  },
  {
    n: '05',
    year: '2025',
    title: 'XDigital',
    subtitle: 'An agency that bills like software, not like a project.',
    description:
      'A Baku digital studio built around subscriptions rather than invoices — websites from $25 a month, social management, and automation work. The client portal is the product: project tracking, billing and direct messaging in one place, with email and WhatsApp alerts. Edge-deployed, Core Web Vitals held green.',
    tags: ['Next.js', 'React Server Components', 'TypeScript', 'Tailwind', 'Edge', 'Vercel'],
    role: 'Engineer & designer',
    client: 'XDigital',
    accent: 'oklch(0.70 0.17 45)',
    accent2: 'oklch(0.89 0.06 60)',
    live: 'https://xdigitale.vercel.app',
    metrics: [
      { value: '3', label: 'service lines' },
      { value: '$25', label: 'entry, per month' },
      { value: '99.9%', label: 'uptime target' },
    ],
    visual: 'agency',
    host: 'xdigitale.vercel.app',
  },
  {
    n: '06',
    year: '2025',
    title: 'Ingla School',
    subtitle: 'One school, four audiences, one coherent front door.',
    description:
      'A Baku education group running language courses and IELTS prep, study-abroad placement across fifty-plus universities, a preschool for ages three to six, and corporate certification. Four audiences who share almost nothing — the work was an information architecture that lets each find their path in one move without the others getting in the way.',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'CMS', 'i18n', 'Vercel'],
    role: 'Engineer & designer',
    client: 'Ingla School',
    accent: 'oklch(0.58 0.14 235)',
    accent2: 'oklch(0.91 0.05 230)',
    live: 'https://www.inglaschool.az',
    metrics: [
      { value: '98%', label: 'hit IELTS target' },
      { value: '750+', label: 'active students' },
      { value: '4.9', label: 'satisfaction' },
    ],
    visual: 'school',
    host: 'inglaschool.az',
  },
  {
    n: '07',
    year: '2025',
    title: 'Varan Colleges',
    subtitle: 'Exam prep and admissions, from Baku to anywhere.',
    description:
      'An education consultancy and language centre: IELTS, TOEFL, SAT, GMAT, GRE, AP and IB coaching alongside university placement across the USA, Canada, UK, Europe, Australia and Turkey. Bilingual throughout, with a blog and university profiles feeding the funnel and a free thirty-minute consultation as the single call to action.',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'i18n', 'MDX', 'Vercel'],
    role: 'Engineer & designer',
    client: 'Varan Colleges',
    accent: 'oklch(0.55 0.11 200)',
    accent2: 'oklch(0.91 0.04 200)',
    live: 'https://www.varancolleges.com/en',
    metrics: [
      { value: '8', label: 'exam tracks' },
      { value: '6', label: 'destinations' },
      { value: '2', label: 'languages' },
    ],
    visual: 'consultancy',
    host: 'varancolleges.com',
  },
  {
    n: '08',
    year: '2024',
    title: 'Asiman Abdullazade',
    subtitle: 'A portfolio that gets out of the photography’s way.',
    description:
      'A folio for a Baku multidisciplinary artist working across photography, film and design. Three numbered rooms, each entered through a single full-bleed image, and almost no interface between the visitor and the work. The restraint was the brief: the images are loud enough on their own.',
    tags: ['Next.js', 'TypeScript', 'next/image', 'Tailwind', 'Vercel'],
    role: 'Engineer & designer',
    client: 'Asiman Abdullazade',
    accent: 'oklch(0.52 0.09 60)',
    accent2: 'oklch(0.90 0.04 70)',
    live: 'https://asimanabdullazade.vercel.app',
    metrics: [
      { value: '3', label: 'disciplines' },
      { value: '01–03', label: 'numbered rooms' },
    ],
    visual: 'gallery',
    host: 'asimanabdullazade.vercel.app',
  },
]

export const STACK: StackItem[] = [
  { name: 'Next.js',        note: 'App router, RSC',       x: 8,  y: 22, size: 1.15 },
  { name: 'React',          note: 'The default canvas',    x: 28, y: 8,  size: 1.1  },
  { name: 'TypeScript',     note: 'End-to-end types',      x: 56, y: 16, size: 1.2  },
  { name: 'Tailwind CSS',   note: 'Design tokens',         x: 78, y: 32, size: 1.05 },
  { name: 'shadcn/ui',      note: 'Composable primitives', x: 18, y: 58, size: 1.0  },
  { name: 'Framer Motion',  note: 'Choreography',          x: 42, y: 70, size: 0.95 },
  { name: 'Node.js',        note: 'API runtime',           x: 64, y: 60, size: 1.05 },
  { name: 'MongoDB',        note: 'Document store',        x: 6,  y: 80, size: 1.0  },
  { name: 'PostgreSQL',     note: 'Source of truth',       x: 84, y: 78, size: 1.1  },
  { name: 'Vercel',         note: 'Where it lives',        x: 36, y: 36, size: 0.95 },
]

export const SOCIAL_LINKS: SocialLink[] = [
  { label: 'GitHub',   handle: '@aydinnasibli', href: 'https://github.com/aydinnasibli' },
  { label: 'LinkedIn', handle: 'aydinnasibli',  href: 'https://www.linkedin.com/in/aydinnasibli' },
  { label: 'X',        handle: '@aydinnasibli', href: 'https://x.com/aydinnasibli' },
  { label: 'Email',    handle: EMAIL,           href: `mailto:${EMAIL}` },
]
